// src/pages/policy/index.vue
<template>
  <div>
    <section
      class="section bg-center bg-fixed effect-section"
      :style="{ backgroundImage: `url(${spacePatterImg})` }"
    >
      <div class="mask theme-bg opacity-9"></div>
      <div class="container">
        <div class="row justify-content-center p-50px-t">
          <div class="col-lg-8 text-center">
            <h2 class="white-color h1 m-20px-b">Privace &amp; Policy</h2>
            <ol class="breadcrumb white justify-content-center">
              <li>
                <NuxtLink :to="localePath('/')">{{ $t('links.go_to_the_main_page') }}</NuxtLink>
              </li>
            </ol>
          </div>
        </div>
      </div>
    </section>

    <section class="section">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-12">
            <div class="card">
              <div class="card-body">
                <p>
                  At Code Matter Studio, accessible from
                  https://codematter.studio/, one of our main priorities is the
                  privacy of our visitors. This Privacy Policy document contains
                  types of information that is collected and recorded by Code
                  Matter Studio and how we use it.
                </p>

                <p>
                  If you have additional questions or require more information
                  about our Privacy Policy, do not hesitate to contact us.
                </p>

                <p>
                  This Privacy Policy applies only to our online activities and
                  is valid for visitors to our website with regards to the
                  information that they shared and/or collect in Code Matter
                  Studio. This policy is not applicable to any information
                  collected offline or via channels other than this website.
                </p>

                <h6 class="p-15px-t">Consent</h6>

                <p>
                  By using our website, you hereby consent to our Privacy Policy
                  and agree to its terms.
                </p>

                <h6 class="p-15px-t">Information we collect</h6>

                <p>
                  The personal information that you are asked to provide, and
                  the reasons why you are asked to provide it, will be made
                  clear to you at the point we ask you to provide your personal
                  information.
                </p>
                <p>
                  If you contact us directly, we may receive additional
                  information about you such as your name, email address, phone
                  number, the contents of the message and/or attachments you may
                  send us, and any other information you may choose to provide.
                </p>
                <p>
                  When you register for an Account, we may ask for your contact
                  information, including items such as name, company name,
                  address, email address, and telephone number.
                </p>

                <h6 class="p-15px-t">How we use your information</h6>

                <p>
                  We use the information we collect in various ways, including
                  to:
                </p>

                <ul>
                  <li>Provide, operate, and maintain our webste</li>
                  <li>Improve, personalize, and expand our webste</li>
                  <li>Understand and analyze how you use our webste</li>
                  <li>
                    Develop new products, services, features, and functionality
                  </li>
                  <li>
                    Communicate with you, either directly or through one of our
                    partners, including for customer service, to provide you
                    with updates and other information relating to the webste,
                    and for marketing and promotional purposes
                  </li>
                  <li>Send you emails</li>
                  <li>Find and prevent fraud</li>
                </ul>

                <h6 class="p-15px-t">Log Files</h6>

                <p>
                  Code Matter Studio follows a standard procedure of using log
                  files. These files log visitors when they visit websites. All
                  hosting companies do this and a part of hosting services'
                  analytics. The information collected by log files include
                  internet protocol (IP) addresses, browser type, Internet
                  Service Provider (ISP), date and time stamp, referring/exit
                  pages, and possibly the number of clicks. These are not linked
                  to any information that is personally identifiable. The
                  purpose of the information is for analyzing trends,
                  administering the site, tracking users' movement on the
                  website, and gathering demographic information. Our Privacy
                  Policy was created with the help of the
                  <a href="https://www.privacypolicygenerator.info"
                    >Privacy Policy Generator</a
                  >
                  and the
                  <a
                    href="https://www.privacypolicyonline.com/privacy-policy-generator/"
                    >Online Privacy Policy Generator</a
                  >.
                </p>

                <h6 class="p-15px-t">Cookies and Web Beacons</h6>

                <p>
                  Like any other website, Code Matter Studio uses 'cookies'.
                  These cookies are used to store information including
                  visitors' preferences, and the pages on the website that the
                  visitor accessed or visited. The information is used to
                  optimize the users' experience by customizing our web page
                  content based on visitors' browser type and/or other
                  information.
                </p>

                <p>
                  For more general information on cookies, please read
                  <a href="https://www.cookieconsent.com/what-are-cookies/"
                    >"What Are Cookies"</a
                  >.
                </p>

                <h6 class="p-15px-t">Google DoubleClick DART Cookie</h6>

                <p>
                  Google is one of a third-party vendor on our site. It also
                  uses cookies, known as DART cookies, to serve ads to our site
                  visitors based upon their visit to www.website.com and other
                  sites on the internet. However, visitors may choose to decline
                  the use of DART cookies by visiting the Google ad and content
                  network Privacy Policy at the following URL –
                  <a href="https://policies.google.com/technologies/ads"
                    >https://policies.google.com/technologies/ads</a
                  >
                </p>

                <h6 class="p-15px-t">Advertising Partners Privacy Policies</h6>

                <p>
                  You may consult this list to find the Privacy Policy for each
                  of the advertising partners of Code Matter Studio.
                </p>

                <p>
                  Third-party ad servers or ad networks uses technologies like
                  cookies, JavaScript, or Web Beacons that are used in their
                  respective advertisements and links that appear on Code Matter
                  Studio, which are sent directly to users' browser. They
                  automatically receive your IP address when this occurs. These
                  technologies are used to measure the effectiveness of their
                  advertising campaigns and/or to personalize the advertising
                  content that you see on websites that you visit.
                </p>

                <p>
                  Note that Code Matter Studio has no access to or control over
                  these cookies that are used by third-party advertisers.
                </p>

                <h6 class="p-15px-t">Third Party Privacy Policies</h6>

                <p>
                  Code Matter Studio's Privacy Policy does not apply to other
                  advertisers or websites. Thus, we are advising you to consult
                  the respective Privacy Policies of these third-party ad
                  servers for more detailed information. It may include their
                  practices and instructions about how to opt-out of certain
                  options.
                </p>

                <p>
                  You can choose to disable cookies through your individual
                  browser options. To know more detailed information about
                  cookie management with specific web browsers, it can be found
                  at the browsers' respective websites.
                </p>

                <h6 class="p-15px-t">
                  CCPA Privacy Rights (Do Not Sell My Personal Information)
                </h6>

                <p>
                  Under the CCPA, among other rights, California consumers have
                  the right to:
                </p>
                <p>
                  Request that a business that collects a consumer's personal
                  data disclose the categories and specific pieces of personal
                  data that a business has collected about consumers.
                </p>
                <p>
                  Request that a business delete any personal data about the
                  consumer that a business has collected.
                </p>
                <p>
                  Request that a business that sells a consumer's personal data,
                  not sell the consumer's personal data.
                </p>
                <p>
                  If you make a request, we have one month to respond to you. If
                  you would like to exercise any of these rights, please contact
                  us.
                </p>

                <h6 class="p-15px-t">GDPR Data Protection Rights</h6>

                <p>
                  We would like to make sure you are fully aware of all of your
                  data protection rights. Every user is entitled to the
                  following:
                </p>
                <p>
                  The right to access – You have the right to request copies of
                  your personal data. We may charge you a small fee for this
                  service.
                </p>
                <p>
                  The right to rectification – You have the right to request
                  that we correct any information you believe is inaccurate. You
                  also have the right to request that we complete the
                  information you believe is incomplete.
                </p>
                <p>
                  The right to erasure – You have the right to request that we
                  erase your personal data, under certain conditions.
                </p>
                <p>
                  The right to restrict processing – You have the right to
                  request that we restrict the processing of your personal data,
                  under certain conditions.
                </p>
                <p>
                  The right to object to processing – You have the right to
                  object to our processing of your personal data, under certain
                  conditions.
                </p>
                <p>
                  The right to data portability – You have the right to request
                  that we transfer the data that we have collected to another
                  organization, or directly to you, under certain conditions.
                </p>
                <p>
                  If you make a request, we have one month to respond to you. If
                  you would like to exercise any of these rights, please contact
                  us.
                </p>

                <h6 class="p-15px-t">Children's Information</h6>

                <p>
                  Another part of our priority is adding protection for children
                  while using the internet. We encourage parents and guardians
                  to observe, participate in, and/or monitor and guide their
                  online activity.
                </p>

                <p>
                  Code Matter Studio does not knowingly collect any Personal
                  Identifiable Information from children under the age of 13. If
                  you think that your child provided this kind of information on
                  our website, we strongly encourage you to contact us
                  immediately and we will do our best efforts to promptly remove
                  such information from our records.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
</template>

<script>
import spacePatterImg from 'assets/img/space-pattern.jpg'
export default {
  layout: 'non-header',

  data() {
    return {
      spacePatterImg: spacePatterImg,
    }
  },
}
</script>

// src/src/app/pages/policy/policy.component.ts
import { Component } from '@angular/core'

@Component({
  selector: 'app-policy',
  templateUrl: './policy.component.html',
  styleUrls: ['./policy.component.scss'],
})
export class PolicyComponent {}

<!-- Page Title -->
<section
  class="section bg-center bg-cover bg-fixed effect-section"
  style="
    background-image: url(assets/img/space-pattern.jpg);
  "
>
  <div class="mask theme-bg opacity-9"></div>
  <div class="container">
    <div class="row justify-content-center p-50px-t">
      <div class="col-lg-8 text-center">
        <h2 class="white-color h1 m-20px-b">Privace &amp; Policy</h2>
        <ol class="breadcrumb white justify-content-center">
          <li><a href="/">Home</a></li>
          <li class="active">Privace &amp; Policy</li>
        </ol>
      </div>
    </div>
  </div>
</section>
<!-- End Page Title -->

<!-- Section -->
<section class="section">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-9">
        <div class="card">
          <div class="card-body">
            <h2 class="h3 m-25px-b">Privacy Policy for Code Matter Studio</h2>
            <p>
              At Code Matter Studio, accessible from https://codematter.studio/,
              one of our main priorities is the privacy of our visitors. This
              Privacy Policy document contains types of information that is
              collected and recorded by Code Matter Studio and how we use it.
            </p>

            <p>
              If you have additional questions or require more information about
              our Privacy Policy, do not hesitate to contact us.
            </p>

            <p>
              This Privacy Policy applies only to our online activities and is
              valid for visitors to our website with regards to the information
              that they shared and/or collect in Code Matter Studio. This policy
              is not applicable to any information collected offline or via
              channels other than this website.
            </p>

            <h6 class="p-15px-t">Consent</h6>
            <p>
              By using our website, you hereby consent to our Privacy Policy and
              agree to its terms.
            </p>

            <h6 class="p-15px-t">Information we collect</h6>
            <p>
              The personal information that you are asked to provide, and the
              reasons why you are asked to provide it, will be made clear to you
              at the point we ask you to provide your personal information.
            </p>
            <p>
              If you contact us directly, we may receive additional information
              about you such as your name, email address, phone number, the
              contents of the message and/or attachments you may send us, and
              any other information you may choose to provide.
            </p>
            <p>
              When you register for an Account, we may ask for your contact
              information, including items such as name, company name, address,
              email address, and telephone number.
            </p>

            <h6 class="p-15px-t">How we use your information</h6>
            <p>
              We use the information we collect in various ways, including to:
            </p>

            <ul>
              <li>Provide, operate, and maintain our webste</li>
              <li>Improve, personalize, and expand our webste</li>
              <li>Understand and analyze how you use our webste</li>
              <li>
                Develop new products, services, features, and functionality
              </li>
              <li>
                Communicate with you, either directly or through one of our
                partners, including for customer service, to provide you with
                updates and other information relating to the webste, and for
                marketing and promotional purposes
              </li>
              <li>Send you emails</li>
              <li>Find and prevent fraud</li>
            </ul>

            <h6 class="p-15px-t">Log Files</h6>
            <p>
              Code Matter Studio follows a standard procedure of using log
              files. These files log visitors when they visit websites. All
              hosting companies do this and a part of hosting services'
              analytics. The information collected by log files include internet
              protocol (IP) addresses, browser type, Internet Service Provider
              (ISP), date and time stamp, referring/exit pages, and possibly the
              number of clicks. These are not linked to any information that is
              personally identifiable. The purpose of the information is for
              analyzing trends, administering the site, tracking users' movement
              on the website, and gathering demographic information. Our Privacy
              Policy was created with the help of the
              <a href="https://www.privacypolicygenerator.info"
                >Privacy Policy Generator</a
              >
              and the
              <a
                href="https://www.privacypolicyonline.com/privacy-policy-generator/"
                >Online Privacy Policy Generator</a
              >.
            </p>

            <h6 class="p-15px-t">Cookies and Web Beacons</h6>
            <p>
              Like any other website, Code Matter Studio uses 'cookies'. These
              cookies are used to store information including visitors'
              preferences, and the pages on the website that the visitor
              accessed or visited. The information is used to optimize the
              users' experience by customizing our web page content based on
              visitors' browser type and/or other information.
            </p>

            <p>
              For more general information on cookies, please read
              <a href="https://www.cookieconsent.com/what-are-cookies/"
                >"What Are Cookies"</a
              >.
            </p>

            <h6 class="p-15px-t">Advertising Partners Privacy Policies</h6>
            <P
              >You may consult this list to find the Privacy Policy for each of
              the advertising partners of Code Matter Studio.</P
            >

            <p>
              Third-party ad servers or ad networks uses technologies like
              cookies, JavaScript, or Web Beacons that are used in their
              respective advertisements and links that appear on Code Matter
              Studio, which are sent directly to users' browser. They
              automatically receive your IP address when this occurs. These
              technologies are used to measure the effectiveness of their
              advertising campaigns and/or to personalize the advertising
              content that you see on websites that you visit.
            </p>

            <p>
              Note that Code Matter Studio has no access to or control over
              these cookies that are used by third-party advertisers.
            </p>

            <h6 class="p-15px-t">Third Party Privacy Policies</h6>

            <p>
              Code Matter Studio's Privacy Policy does not apply to other
              advertisers or websites. Thus, we are advising you to consult the
              respective Privacy Policies of these third-party ad servers for
              more detailed information. It may include their practices and
              instructions about how to opt-out of certain options.
            </p>

            <p>
              You can choose to disable cookies through your individual browser
              options. To know more detailed information about cookie management
              with specific web browsers, it can be found at the browsers'
              respective websites.
            </p>

            <h6 class="p-15px-t">
              CCPA Privacy Rights (Do Not Sell My Personal Information)
            </h6>

            <p>
              Under the CCPA, among other rights, California consumers have the
              right to:
            </p>
            <p>
              Request that a business that collects a consumer's personal data
              disclose the categories and specific pieces of personal data that
              a business has collected about consumers.
            </p>
            <p>
              Request that a business delete any personal data about the
              consumer that a business has collected.
            </p>
            <p>
              Request that a business that sells a consumer's personal data, not
              sell the consumer's personal data.
            </p>
            <p>
              If you make a request, we have one month to respond to you. If you
              would like to exercise any of these rights, please contact us.
            </p>

            <h6 class="p-15px-t">GDPR Data Protection Rights</h6>

            <p>
              We would like to make sure you are fully aware of all of your data
              protection rights. Every user is entitled to the following:
            </p>
            <p>
              The right to access – You have the right to request copies of your
              personal data. We may charge you a small fee for this service.
            </p>
            <p>
              The right to rectification – You have the right to request that we
              correct any information you believe is inaccurate. You also have
              the right to request that we complete the information you believe
              is incomplete.
            </p>
            <p>
              The right to erasure – You have the right to request that we erase
              your personal data, under certain conditions.
            </p>
            <p>
              The right to restrict processing – You have the right to request
              that we restrict the processing of your personal data, under
              certain conditions.
            </p>
            <p>
              The right to object to processing – You have the right to object
              to our processing of your personal data, under certain conditions.
            </p>
            <p>
              The right to data portability – You have the right to request that
              we transfer the data that we have collected to another
              organization, or directly to you, under certain conditions.
            </p>
            <p>
              If you make a request, we have one month to respond to you. If you
              would like to exercise any of these rights, please contact us.
            </p>

            <h6 class="p-15px-t">Children's Information</h6>

            <p>
              Another part of our priority is adding protection for children
              while using the internet. We encourage parents and guardians to
              observe, participate in, and/or monitor and guide their online
              activity.
            </p>

            <p>
              Code Matter Studio does not knowingly collect any Personal
              Identifiable Information from children under the age of 13. If you
              think that your child provided this kind of information on our
              website, we strongly encourage you to contact us immediately and
              we will do our best efforts to promptly remove such information
              from our records.
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- End Section -->
